productdb:
 image: mongo:latest
 restart: always
 container_name: "productdb"
 ports:
  - "27017:27017"
 volumes:
  - ./Document_InfoProducts.js:/docker-entrypoint-initdb.d/Document_InfoProducts.js:ro

infoproductservice:
 build: .
 dockerfile: Dockerfile
 container_name: infoproductservice
 ports: 
  - "8082:8080"
 links:
  - productdb